# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tictactoe.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'tictactoe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftictactoe.proto\x12\ttictactoe\"2\n\x0bGameRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12\x10\n\x08position\x18\x02 \x01(\x05\"i\n\x11GameStateResponse\x12\r\n\x05\x62oard\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tyour_turn\x18\x03 \x01(\x08\x12\x11\n\tgame_over\x18\x04 \x01(\x08\x12\x0e\n\x06winner\x18\x05 \x01(\t2S\n\tTicTacToe\x12\x46\n\nGameStream\x12\x16.tictactoe.GameRequest\x1a\x1c.tictactoe.GameStateResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tictactoe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMEREQUEST']._serialized_start=30
  _globals['_GAMEREQUEST']._serialized_end=80
  _globals['_GAMESTATERESPONSE']._serialized_start=82
  _globals['_GAMESTATERESPONSE']._serialized_end=187
  _globals['_TICTACTOE']._serialized_start=189
  _globals['_TICTACTOE']._serialized_end=272
# @@protoc_insertion_point(module_scope)
