# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tictactoe_pb2 as tictactoe__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tictactoe_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TicTacToeStub(object):
    """serviço principal do jogo
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GameStream = channel.stream_stream(
                '/tictactoe.TicTacToe/GameStream',
                request_serializer=tictactoe__pb2.GameRequest.SerializeToString,
                response_deserializer=tictactoe__pb2.GameStateResponse.FromString,
                _registered_method=True)


class TicTacToeServicer(object):
    """serviço principal do jogo
    """

    def GameStream(self, request_iterator, context):
        """Um stream bidirecional para o jogo.
        O cliente envia eventos de jogada e o servidor envia atualizações do estado do jogo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TicTacToeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GameStream': grpc.stream_stream_rpc_method_handler(
                    servicer.GameStream,
                    request_deserializer=tictactoe__pb2.GameRequest.FromString,
                    response_serializer=tictactoe__pb2.GameStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tictactoe.TicTacToe', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tictactoe.TicTacToe', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TicTacToe(object):
    """serviço principal do jogo
    """

    @staticmethod
    def GameStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/tictactoe.TicTacToe/GameStream',
            tictactoe__pb2.GameRequest.SerializeToString,
            tictactoe__pb2.GameStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
