# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tictactoe.proto for package 'tictactoe'

require 'grpc'
require_relative 'tictactoe_pb'

module Tictactoe
  module TicTacToe
    # serviço principal do jogo
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'tictactoe.TicTacToe'

      # Um stream bidirecional para o jogo.
      # O cliente envia eventos de jogada e o servidor envia atualizações do estado do jogo.
      rpc :GameStream, stream(::Tictactoe::GameRequest), stream(::Tictactoe::GameStateResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
