# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tictactoe.proto

require 'google/protobuf'


descriptor_data = "\n\x0ftictactoe.proto\x12\ttictactoe\"2\n\x0bGameRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12\x10\n\x08position\x18\x02 \x01(\x05\"i\n\x11GameStateResponse\x12\r\n\x05\x62oard\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tyour_turn\x18\x03 \x01(\x08\x12\x11\n\tgame_over\x18\x04 \x01(\x08\x12\x0e\n\x06winner\x18\x05 \x01(\t2S\n\tTicTacToe\x12\x46\n\nGameStream\x12\x16.tictactoe.GameRequest\x1a\x1c.tictactoe.GameStateResponse(\x01\x30\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Tictactoe
  GameRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tictactoe.GameRequest").msgclass
  GameStateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tictactoe.GameStateResponse").msgclass
end
